Adding Shortcut.com support
mikaelvesavuori/dorametrix pull request #23
Opened 2023-03-15 22:20 UTC by jprosenbaum

The ASYNC changes are needed because the Shortcut webhook only sends what is changed not the entire payload
A call must be made back to the API to get the full story for parsing

2023-03-19 14:07 UTC, mikaelvesavuori requested changes
Took a first stab at this - great idea! There are still some number of issues - many smaller, but also some bigger ones like checked-in secrets - that we need to address. Once we fix these issues I'll just run a deployment and tiny manual verification to see it all works.

2023-03-19 14:07 UTC, mikaelvesavuori commented on jest.env.js
> +process.env.SHORTCUT_TOKEN = "7c874900-b038-4ac8-89d6-813d6daea148";
This needs to be addressed. Don't want any hardcoded secrets in checked-in code ;) See if you can pick this some other way.

2023-03-19 14:07 UTC, mikaelvesavuori commented on package.json
> +    "axios": "1.3.4",
I'd much prefer if we can use Node-native `fetch` or if absolutely required, something lighter like `cross-fetch`.

2023-03-19 14:07 UTC, mikaelvesavuori commented on serverless.yml
> +    shortcutIncidentLabelId: ${opt:shortcutToken, '2805'} # Set this to your value if you want to use a fallback value
There are a few ways to solve these hardcoded values.

The easiest would be to remove the fallback for the `shortcutToken` - you could then proceed to documenting in the `README` that one has to be provided, lest the user manually changes `serverless.yml` to work in this way (as per above).

If you'd ask if it weren't hypocritical allowing the above two values, I'd respond those are OK as they are clearly fictional (account number) and the API key is because we should probably supply one for zero-config cases.

As for the label ID, I will take it this isn't "secret" in any way but the value seems really magical. Can we explain what is special about the particular value `2805`?

2023-03-19 14:07 UTC, mikaelvesavuori commented on src/application/getParser.ts
> +  const signature = 'Clubhouse-Signature' in (headers || {}) || 'Shortcut-Signature' in (headers || {});
For stylistic reasons, you should probably keep this formatted in the way above, though I could live with this, given it's a lot more complicated than an A/B switch.

2023-03-19 14:07 UTC, mikaelvesavuori commented on src/application/parsers/ShortcutParser.ts
> +
Remove this empty line.

2023-03-19 14:07 UTC, mikaelvesavuori commented on src/application/parsers/ShortcutParser.ts
> +    this.shortcutToken = process.env.SHORTCUT_TOKEN ?? "11111111-1111-1111-1111-111111111111"
I'd recommend having this throw a unique error instead if it's empty so we can avoid coded fallbacks.

2023-03-19 14:07 UTC, mikaelvesavuori commented on src/application/parsers/ShortcutParser.ts
> +    const parseIntValue = (value : any, defaultValue : number) : number => {
Please lift this as a dedicated function in `frameworks` so we keep the parser classes clean.

2023-03-19 14:07 UTC, mikaelvesavuori commented on src/application/parsers/ShortcutParser.ts
> +    if(Object.keys(this.storyData).length > 0) return this.storyData;
Add space between `if` and `(Object.keys(...)`

2023-03-19 14:07 UTC, mikaelvesavuori commented on src/application/parsers/ShortcutParser.ts
> +    return axios.get("https://api.app.shortcut.com/api/v3/stories/" + id, { headers: {"Shortcut-Token" : this.shortcutToken}})
Not sure what's going on with the linter here - please following the provided linting conventions (if they work?).

2023-03-19 14:07 UTC, mikaelvesavuori commented on src/application/parsers/ShortcutParser.ts
> +    return axios.get("https://api.app.shortcut.com/api/v3/stories/" + id, { headers: {"Shortcut-Token" : this.shortcutToken}})
Again, please replace `axios` with (ideally) native Node `fetch` or `cross-fetch`.

2023-03-19 14:07 UTC, mikaelvesavuori commented on src/application/parsers/ShortcutParser.ts
> +
Remove empty line.

2023-03-19 14:07 UTC, mikaelvesavuori commented on src/application/parsers/ShortcutParser.ts
> +      if(body?.['completed'] == true) return "closed";
There are quite some number of places where it seems the linter + `prettier` isn't working - thinking of weird and jumpy formatting and non-spaces between `if`s and values... We can certainly prettify things on my end but it seems antithetical.

2023-03-19 14:07 UTC, mikaelvesavuori commented on tests/unit/application/JiraParser.test.ts
> -      expect(() =>
I think that these can and should stay in the more-or-less same format they had before. See https://jestjs.io/docs/tutorial-async#rejects

2023-03-19 14:07 UTC, mikaelvesavuori commented on src/domain/valueObjects/Event.ts
> +  changes: Change[] = new Array<Change>(0);
Seems like we can simplify this by having it simply as `changes: Change[] = [];`.

2023-03-19 14:07 UTC, mikaelvesavuori commented on tests/unit/application/JiraParser.test.ts
> -      expect(() =>
It's just more semantic and easier-to-read, I suppose, would be the driving argument here.

2023-03-19 14:08 UTC, mikaelvesavuori commented
Note that for some things, especially of stylistic nature, I've not commented on every occasion of these, but taken some indicative notes where relevant.

2023-03-20 22:14 UTC, jprosenbaum commented on serverless.yml
> +    shortcutIncidentLabelId: ${opt:shortcutToken, '2805'} # Set this to your value if you want to use a fallback value
When you create a label in shortcut it assigns an id to that label.  2805 is the id created in our system. 
I will update the readme

2023-03-21 21:06 UTC, jprosenbaum commented on package.json
> +    "axios": "1.3.4",
I had an issue getting fetch to work and then mock out. I used cross-fetch

2023-03-21 21:06 UTC, jprosenbaum commented on serverless.yml
> +    shortcutIncidentLabelId: ${opt:shortcutToken, '2805'} # Set this to your value if you want to use a fallback value
removed hard coded references and updated the readme

2023-03-21 21:07 UTC, jprosenbaum commented on src/application/parsers/ShortcutParser.ts
> +      if(body?.['completed'] == true) return "closed";
I was able to linter and prettier

2023-03-21 21:08 UTC, jprosenbaum commented on src/application/getParser.ts
> +  const signature = 'Clubhouse-Signature' in (headers || {}) || 'Shortcut-Signature' in (headers || {});
I removed the old Clubhouse signature to simplify

2023-03-21 21:12 UTC, jprosenbaum commented on src/application/parsers/ShortcutParser.ts
> +    return axios.get("https://api.app.shortcut.com/api/v3/stories/" + id, { headers: {"Shortcut-Token" : this.shortcutToken}})
ran linter and committed changes

2023-03-21 21:21 UTC, jprosenbaum commented on src/application/parsers/ShortcutParser.ts
> +    const parseIntValue = (value : any, defaultValue : number) : number => {
I believe I made the necessary change for this

2023-03-22 15:32 UTC, jprosenbaum commented
@mikaelvesavuori thanks for working with me on this, I have learned a lot working through this.

2023-03-29 11:20 UTC, mikaelvesavuori commented
Hey! Sorry for taking some time to respond. I will look at your later contributions shortly. Please see if you can integrate any changes from main before I review.

2023-03-30 14:02 UTC, jprosenbaum commented
No problem, it gave me time to find some issues in the code and do some cleanup.
Main has integrated into the PR

2023-04-04 18:50 UTC, mikaelvesavuori commented
OK, so this is merged (or will be merged). Quite a number of changes added from my sides that were easier to spot and address in the IDE rather than in the online review interface.

Thanks for your work - it will be out in `2.2.2` shortly!

2023-04-04 18:51 UTC, merged